### ISSUE TITLE
Invalid wiki collection URL

### ISSUE THREAD

**Issue by Ginko-sensei** [Minimalist3/GranblueParty#11]
When trying to import my wiki collection by copy-pasting the URL, I get an "Invalid wiki collection URL" error message.
If I replace the dots by semicolons in the part after the #, the import works.

Also, it's a minor problem but in the box that opens after clicking "Load Wiki collection", there is a 'Username' string displayed in the background of the text box, even though we must enter an URL.

**Comment by Minimalist3** [comment]
Thanks for the bug report.
It should be fixed, now.
