### ISSUE TITLE
[Feature Request] Hard Pro in the Dailies List

### ISSUE THREAD

**Issue by thekenoh** [Minimalist3/GranblueParty#17]
Hey hey, thanks for the site, it's great :> I was just wondering if there could be a button for Hard+ Pro (all Hard+ Raids automatically cleared all at once) in the Dailies checklist feature. Thanks!

**Comment by Minimalist3** [comment]
Good idea, I'll add it with the next update.

**Comment by Minimalist3** [comment]
Hard+ Pro is now in the Dailies list
2d623a711a94c71dff41458e3768a6cd79349863
