### ISSUE TITLE
API seems to be public

### ISSUE THREAD

**Issue by jesuscc1993** [Minimalist3/GranblueParty#6]
I just tried running a GET request to https://www.granblue.party/api/party/summons from Postman and it ran. This means I could write my own support summon generator using your API if I wanted to, which I'd assume you wouldn't want.

**Comment by Minimalist3** [comment]
To my knowledge, that's how every API works. Think of it as a resource, like a jpg image.
I could filter on the Referrer, but it's very easy to fool such protection.
Given how niche the site is, I'd say it's better to let the API be open than adding unnecessary load to the server.
