### ISSUE TITLE
Spark Maker is not being updated in a timely fashion

### ISSUE THREAD

**Issue by Maruhai** [Minimalist3/GranblueParty#66]
Hello,  
Thank you for Granblue.party, I appreciate the effort behind the website and have used the Spark Maker for years, I consider it better than other options.  
However it has become increasingly frustrating and annoying to use as the newly released units are never added in a timely fashion to the list, making me have to do a "first draft" picture, then having to come back to them days (weeks?) later to "correct them" for archiving.  
I understand not having the time to update the db, or not wanting to do it. But if that is the case, could you please give the reins to someone else to do it? It's frustrating having to stop using an otherwise great service because it just isn't being maintained.  
Thank you.

**Comment by Minimalist3** [comment]
Hello,
I understand the frustration. I need to find a way to be notified when a new banner is released.
I'll try some calendar reminders first. It should help.

**Comment by Maruhai** [comment]
Hello,
Are you really not willing to try to find a way to automate this? I can understand you're not invested in the game anymore, it's totally fair, but being late right now, during the time of the year where spark makers see the most use, is really sad for the tool.
